// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddAP(arg1:main.AP):Promise<void>;

export function AddSta(arg1:main.Sta):Promise<void>;

export function GenerateJSON():Promise<boolean>;
