// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GenerateJSON(arg1:main.Input):Promise<boolean>;

export function Greet(arg1:string):Promise<string>;
