// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAP(arg1) {
  return window['go']['main']['App']['AddAP'](arg1);
}

export function AddSta(arg1) {
  return window['go']['main']['App']['AddSta'](arg1);
}

export function GenerateJSON() {
  return window['go']['main']['App']['GenerateJSON']();
}
