// Package python generates python code for Mininet.
package python

/**
This file is responsible for Python Topo script generation

Future improvements: Add consistency into python script generation
*/

import (
	"fmt"
	"strings"

	"github.com/CMU-99P-Fall25-Practicum/Omen/modules/spawn_topology/models"
)

// TopologyScript generates a mininet topology script from the given hosts, switches, and links.
// The returned string is a topology script that can be passed to mininet as `--topo=fromjson`.
func TopologyScript(hosts, switches []models.Node, links []models.Link) string {
	return fmt.Sprintf(`# Auto-generated by Omen Mininet spawn_topology

from mininet.topo import Topo

class FromJSON(Topo):
    def build(self):
%s
%s
%s

topos = { 'fromjson': ( lambda: FromJSON() ) }
`,
		addHosts(8, hosts), addSwitches(switches), addLinks(links))
}

// Add tap for the python script
// It's currently using four spaces " " instead of one tap for consistency
func addTap(tapNum int) string {
	tap := "    "
	return strings.Repeat(tap, tapNum)
}

// addHosts generates one line for each host, where the host adds itself to the topology.
// indentLevel is the number of spaces to insert before the command (to ensure proper indentation).
func addHosts(indentLevel int, hosts []models.Node) string {
	var sb strings.Builder
	indent := strings.Repeat(" ", indentLevel)
	for _, h := range hosts {
		fmt.Fprintf(&sb, indent+"%[1]s = self.addHost('%[1]s')\n", h.ID)
	}
	return sb.String()
}

// Generate Python code for adding switches
func addSwitches(sw []models.Node) string {
	s := ""
	for _, x := range sw {
		s += addTap(2) + fmt.Sprintf("%[1]s = self.addSwitch('%[1]s')\n", x.ID)
	}
	return s
}

// Generate Python code for adding links
func addLinks(links []models.Link) string {
	s := ""
	for _, lk := range links {
		s += addTap(2) + fmt.Sprintf("self.addLink(%s, %s)\n", lk.NodeIDA, lk.NodeIDB)
	}
	return s
}
