// Package python generates python code for Mininet.
package python

import (
	"fmt"
	"strings"
)

// TopologyScript generates a mininet topology script from the given hosts, switches, and links.
// The returned string is a topology script that can be passed to mininet as `--topo=fromjson`.
func TopologyScript(hosts, switches []string, links [][2]string) string {
	return fmt.Sprintf(`# Auto-generated by Omen Mininet spawn_topology

from mininet.topo import Topo

class FromJSON(Topo):
    def build(self):
%s
%s
%s

topos = { 'fromjson': ( lambda: FromJSON() ) }
`,
		addHosts(8, hosts), addSwitches(switches), addLinks(links))
}

// addHosts generates one line for each host, where the host adds itself to the topology.
// indentLevel is the number of spaces to insert before the command (to ensure proper indentation).
func addHosts(indentLevel int, hosts []string) string {
	var sb strings.Builder
	indent := strings.Repeat(" ", indentLevel)
	for _, h := range hosts {
		fmt.Fprintf(&sb, indent+"%[1]s = self.addHost('%[1]s')\n", h)
	}
	return sb.String()
}

// Generate Python code for adding switches
func addSwitches(sw []string) string {
	s := ""
	for _, x := range sw {
		s += fmt.Sprintf("        %[1]s = self.addSwitch('%[1]s')\n", x)
	}
	return s
}

// Generate Python code for adding links
func addLinks(links [][2]string) string {
	s := ""
	for _, lk := range links {
		s += fmt.Sprintf("        self.addLink(%s, %s)\n", lk[0], lk[1])
	}
	return s
}
