{
 "title": "Timeframe 1",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Map",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "queryText": "SELECT\n  id AS node_id,\n  title,\n  latitude,\n  longitude,\n  detail__success_rate AS success_rate\nFROM netB_nodes\nWHERE latitude IS NOT NULL AND longitude IS NOT NULL;",
     "rawQueryText": "SELECT\n  id AS node_id,\n  title,\n  latitude,\n  longitude,\n  detail__success_rate AS success_rate\nFROM netB_nodes\nWHERE latitude IS NOT NULL AND longitude IS NOT NULL;"
    },
    {
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Topology",
   "type": "nodeGraph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "queryText": "SELECT\n  id,\n  title,\n  subTitle,\n  mainStat,\n  severity,\n  \"detail__rx_bytes\",\n  \"detail__rx_packets\",\n  \"detail__tx_bytes\",\n  \"detail__tx_packets\",\n  \"detail__success_rate\",\n  \"arc__success\",\n  \"arc__errors\"\nFROM netB_nodes\nLIMIT 50;",
     "rawQueryText": "SELECT\n  id,\n  title,\n  subTitle,\n  mainStat,\n  severity,\n  \"detail__rx_bytes\",\n  \"detail__rx_packets\",\n  \"detail__tx_bytes\",\n  \"detail__tx_packets\",\n  \"detail__success_rate\",\n  \"arc__success\",\n  \"arc__errors\"\nFROM netB_nodes\nLIMIT 50;"
    },
    {
     "queryText": "SELECT\n  id,      \n  source,    \n  target,    \n  status\nFROM netB_edges;",
     "rawQueryText": "SELECT\n  id,      \n  source,    \n  target,    \n  status\nFROM netB_edges;"
    }
   ]
  },
  {
   "title": "Metrics",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "queryText": "SELECT * FROM netB_timeseries;",
     "rawQueryText": "SELECT * FROM netB_timeseries;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}